# Compose file for a dev environment
services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80 # optional
      APP_HOST: 0.0.0.0 # optional
      WORKER_API_URL: "api:80"
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80

  api:
    build:
      context: api/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80 # optional
      DATABASE_URL: "mysql://api:CHANGEME@db/api"
    depends_on:
      - db
    # ports:
    #   - 127.0.0.1:3000:80

  db:
    image: mysql:8.4
    environment:
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "CHANGEME"
      MYSQL_DATABASE: "api"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d
