# Compose file for a dev environment
services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production # optional
      PORT: 80 # optional
      HOST: 0.0.0.0 # optional
      NUXT_PUBLIC_API_BASE: "http://api/api"
    ports:
      - 127.0.0.1:3000:80

  api:
    build:
      context: api/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80 # optional
      DATABASE_URL: "postgresql://api:CHANGEME@db/api"
    # ports:
    #   - 127.0.0.1:3001:80

  db:
    image: bitnami/postgresql:15
    environment:
      POSTGRESQL_USERNAME: "api"
      POSTGRESQL_PASSWORD: "CHANGEME"
      POSTGRESQL_DATABASE: "api"
    ports:
      - 127.0.0.1:5432:5432
    # alternative to using `sqlx migrate run` to populate the DB on first run
    volumes:
      - ./api/migrations:/docker-entrypoint-initdb.d
