# Compose file for a dev environment
services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80 # optional
      APP_HOST: 0.0.0.0 # optional
      WORKER_API_URL: "api:80"
    depends_on:
      - api
    ports:
      - 127.0.0.1:8000:80

  api:
    build:
      context: api/
      dockerfile: Dockerfile
    environment:
      APP_PORT: 80 # optional
      DATABASE_URL: "postgresql://api:CHANGEME@db/api"
    depends_on:
      - db
    # ports:
    #   - 127.0.0.1:3000:80

  db:
    image: bitnami/postgresql:15
    environment:
      POSTGRESQL_USERNAME: "api"
      POSTGRESQL_PASSWORD: "CHANGEME"
      POSTGRESQL_DATABASE: "api"
    ports:
      - 127.0.0.1:5432:5432
