apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: mfe-web
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: front-deployment
      namespace: mfe-web
  template:
    metadata:
      labels:
        name: front-deployment
        namespace: mfe-web
    spec:
      containers:
        - name: nuxtapp
          image: ghcr.io/do3-2023/mfe-kube/web:latest
          imagePullPolicy: Always
          env:
            - name: NUXT_PUBLIC_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: front-config
                  key: apiBase
          ports:
            - containerPort: 80
