apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: mfe-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: web-deployment
      namespace: mfe-web
  template:
    metadata:
      labels:
        name: web-deployment
        namespace: mfe-web
    spec:
      containers:
        - name: nuxt-app
          image: ghcr.io/do3-2023/mfe-kube/web:latest
          imagePullPolicy: Always
          env:
            - name: NUXT_PUBLIC_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: apiBase
          ports:
            - name: nuxt-pod-port
              containerPort: 80
