apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: mfe-web
spec:
  type: NodePort
  selector:
    name: front-deployment
    namespace: mfe-web
  ports:
    - name: front-port
      protocol: TCP
      port: 80
      targetPort: 80
