apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mfe-web
spec:
  type: NodePort
  selector:
    name: web-deployment
    namespace: mfe-web
  ports:
    - name: web-port
      port: 80
      targetPort: web-pod-port
