[package]
name = "mfe-api"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
# http server
axum = { version = "0.7", features = ["json", "macros"] }
axum-extra = "0.9"
tokio = { version = "1.38", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# db & serde
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.18", features = ["derive"] }

# utility crates
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = "0.3"
dotenvy = "0.15"
