# Compose file for a dev environment
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     APP_PORT: 80 # optional
  #     DATABASE_URL: "postgresql://api:CHANGEME@db/api"
  #   ports:
  #     - 127.0.0.1:3000:80

  db:
    image: bitnami/postgresql:15
    environment:
      POSTGRESQL_USERNAME: "api"
      POSTGRESQL_PASSWORD: "CHANGEME"
      POSTGRESQL_DATABASE: "api"
    ports:
      - 127.0.0.1:5432:5432
