name: API module workflow (check & build push docker)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      SQLX_OFFLINE: true
    steps:
      - uses: actions/checkout@v4

      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Use cached dependencies and artifacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./api

      - name: Check formatting
        run: cargo fmt --check
        working-directory: ./api

      - name: Run lint
        run: cargo clippy -- -D warnings
        working-directory: ./api

  build_and_push:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker.yml
    with:
      path: ./api
      image: ghcr.io/${{ github.repository }}/api
